content_dir: content
default_template: default.html.jinja2
globals_: {}
jinja_env_kwargs: {}
output_dir: docs
pandoc_fmt_from: markdown+smart
pandoc_fmt_to: html
pandoc_kwargs:
  mathjax: true
resources_dir: resources
templates_dir: templates

